[project]
name = "python"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "adbc-driver-flightsql>=1.7.0",
    "pyarrow>=21.0.0",
]
