apiVersion: v1
kind: Secret
metadata:
  name: {{ include "sqlflite.fullname" . }}-secret
  labels:
    {{- include "sqlflite.labels" . | nindent 4 }}
type: Opaque
data:
{{ (.Files.Glob "secrets/opaque/*").AsSecrets | indent 2 }}
