apiVersion: v1
kind: Service
metadata:
  name: {{ include "gizmosql.fullname" . }}
  labels:
    {{- include "gizmosql.labels" . | nindent 4 }}
spec:
  type: {{ .Values.gizmoSQLServer.service.type }}
  ports:
    - port: {{ .Values.gizmoSQLServer.service.port }}
      targetPort: gizmosql-port
      protocol: TCP
      name: gizmosql-port
  selector:
    {{- include "gizmosql.selectorLabels" . | nindent 4 }}
    app: gizmosql-server
