apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "sqlflite.fullname" . }}-server
  labels:
    {{- include "sqlflite.labels" . | nindent 4 }}
    app: sqlflite-server
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "sqlflite.selectorLabels" . | nindent 6 }}
      app: sqlflite-server
  serviceName: sqlflite
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/global-secret.yaml") . | sha256sum }}
        {{- with .Values.sqlFliteServer.podAnnotations }}
          {{- toYaml . | nindent 8 }}
        {{- end }}
      labels:
        {{- include "sqlflite.selectorLabels" . | nindent 8 }}
        app: sqlflite-server
    spec:
      {{- with .Values.sqlFliteServer.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.sqlFliteServer.podSecurityContext | nindent 8 }}
      volumes:
# See: https://aws.amazon.com/blogs/containers/eks-persistent-volumes-for-instance-store/ for details on using local NVMe for supported nodes
# Uncomment the following lines to mount the local NVMe disk as a data volume
#        - name: nvme-volume
#          hostPath:
#            # directory location on host
#            path: /nvme/disk
#            # this field is optional
#            type: Directory
        - name: tls-volume
          secret:
            secretName: {{ include "sqlflite.fullname" . }}-tls-secret
            optional: true
# Uncomment the following lines to mount the local NVMe disk as a data volume
#      initContainers:
#        - name: volume-mount-chmod
#          image: busybox
#          command: [ "sh", "-c", "chmod 777 /data" ]
#          volumeMounts:
#            - name: nvme-volume
#              mountPath: /data
      containers:
        - name: sqlflite
          volumeMounts:
# Uncomment the following lines to mount the local NVMe disk as a data volume
#            - name: nvme-volume
#              mountPath: /opt/sqlflite/data
            - name: tls-volume
              mountPath: /opt/sqlflite/tls
              readOnly: true
          env:
            - name: DATABASE_BACKEND
              value: duckdb
            - name: DATABASE_FILENAME
              value: {{ .Values.sqlFliteServer.config.DATABASE_FILENAME }}
            - name: SQLFLITE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "sqlflite.fullname" . }}-secret
                  key: SQLFLITE_PASSWORD
                  optional: false
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: {{ include "sqlflite.fullname" . }}-secret
                  key: AWS_ACCESS_KEY_ID
                  optional: true
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ include "sqlflite.fullname" . }}-secret
                  key: AWS_SECRET_ACCESS_KEY
                  optional: true
            - name: AWS_SESSION_TOKEN
              valueFrom:
                secretKeyRef:
                  name: {{ include "sqlflite.fullname" . }}-secret
                  key: AWS_SESSION_TOKEN
                  optional: true
            - name: AWS_DEFAULT_REGION
              valueFrom:
                secretKeyRef:
                  name: {{ include "sqlflite.fullname" . }}-secret
                  key: AWS_DEFAULT_REGION
                  optional: true
          securityContext:
            {{- toYaml .Values.sqlFliteServer.securityContext | nindent 12 }}
          image: "{{ .Values.sqlFliteServer.image.repository }}:{{ .Values.sqlFliteServer.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.sqlFliteServer.image.pullPolicy }}
          ports:
            - name: sqlflite-port
              containerPort: {{ .Values.sqlFliteServer.service.port }}
              protocol: TCP
#          livenessProbe:
#            httpGet:
#              path: /
#              port: http
#          readinessProbe:
#            httpGet:
#              path: /
#              port: http
          resources:
            {{- toYaml .Values.sqlFliteServer.resources | nindent 12 }}
      {{- with .Values.sqlFliteServer.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.sqlFliteServer.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.sqlFliteServer.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
